name: Generate Android Keystore

on:
  workflow_dispatch:

jobs:
  generate-keystore:
    runs-on: ubuntu-latest

    steps:
      - name: Generate Keystore
        run: |
          keytool -genkey -v -keystore my-release-key.keystore -alias goalrewardkey -keyalg RSA -keysize 2048 -validity 10000 -storepass ASDfefae#3r22f#Z -keypass ASDfefae#3r22f#Z -dname "CN=GoalRewardTracker, OU=Dev, O=PrimeEdgeFitness, L=City, S=State, C=US"
          base64 my-release-key.keystore > encoded_keystore.txt
          cat encoded_keystore.txt
